[2023-03-13T19:31:04.768+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-13T19:31:04.780+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-13T19:31:04.780+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:31:04.780+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:31:04.780+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:31:04.801+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:27+00:00
[2023-03-13T19:31:04.804+0000] {standard_task_runner.py:55} INFO - Started process 35085 to run task
[2023-03-13T19:31:04.808+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:27+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpsulqu28q']
[2023-03-13T19:31:04.810+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:31:04.881+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [running]> on host dev
[2023-03-13T19:31:04.948+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:27+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:27+00:00
[2023-03-13T19:31:04.950+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:31:04.951+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/usr/bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:31:04.960+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:31:04.962+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: /usr/bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:31:04.962+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:31:04.973+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:31:04.978+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000027, start_date=20230313T193104, end_date=20230313T193104
[2023-03-13T19:31:04.998+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 25 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 35085)
[2023-03-13T19:31:05.019+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:31:05.037+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T19:41:38.917+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-13T19:41:38.930+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-13T19:41:38.930+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:41:38.930+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:41:38.930+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:41:38.951+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:27+00:00
[2023-03-13T19:41:38.954+0000] {standard_task_runner.py:55} INFO - Started process 37096 to run task
[2023-03-13T19:41:38.958+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:27+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpy2j0d1u4']
[2023-03-13T19:41:38.960+0000] {standard_task_runner.py:83} INFO - Job 73: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:41:39.026+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [running]> on host dev
[2023-03-13T19:41:39.094+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:27+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:27+00:00
[2023-03-13T19:41:39.096+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:41:39.097+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:41:39.105+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:41:39.106+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:41:39.107+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:41:39.117+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:41:39.121+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000027, start_date=20230313T194138, end_date=20230313T194139
[2023-03-13T19:41:39.138+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 73 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 37096)
[2023-03-13T19:41:39.169+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:41:39.195+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T20:03:06.261+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-13T20:03:06.285+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-13T20:03:06.286+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:03:06.286+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:03:06.286+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:03:06.468+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:27+00:00
[2023-03-13T20:03:06.471+0000] {standard_task_runner.py:55} INFO - Started process 40860 to run task
[2023-03-13T20:03:06.476+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:27+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp93t4gpts']
[2023-03-13T20:03:06.478+0000] {standard_task_runner.py:83} INFO - Job 185: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:03:07.177+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [running]> on host dev
[2023-03-13T20:03:08.264+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:27+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:27+00:00
[2023-03-13T20:03:08.266+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:03:08.267+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash -f /home/dev/etc/logstash/conf.d/data.conf']
[2023-03-13T20:03:08.276+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:03:08.277+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T20:03:08.277+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T20:03:08.317+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T20:03:08.321+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000027, start_date=20230313T200306, end_date=20230313T200308
[2023-03-13T20:03:08.343+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 185 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 40860)
[2023-03-13T20:03:08.372+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T20:03:08.392+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T20:34:22.214+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-13T20:34:22.227+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-13T20:34:22.228+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:34:22.228+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:34:22.228+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:34:22.250+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:27+00:00
[2023-03-13T20:34:22.253+0000] {standard_task_runner.py:55} INFO - Started process 47302 to run task
[2023-03-13T20:34:22.258+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:27+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpexvglr2m']
[2023-03-13T20:34:22.260+0000] {standard_task_runner.py:83} INFO - Job 297: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:34:22.334+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [running]> on host dev
[2023-03-13T20:34:22.437+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:27+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:27+00:00
[2023-03-13T20:34:22.439+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:34:22.440+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-13T20:34:22.449+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:34:22.582+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-13T20:34:22.892+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-13T20:34:47.528+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-13T20:34:47.668+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:47,664][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-13T20:34:47.682+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:47,682][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-13T20:34:48.208+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:48,208][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-13T20:34:50.095+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:50,093][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-13T20:34:51.155+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:51,154][INFO ][org.reflections.Reflections] Reflections took 158 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-13T20:34:52.762+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:52,762][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-13T20:34:53.306+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:53,303][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-13T20:34:53.547+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:53,547][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-13T20:34:53.609+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:53,608][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-13T20:34:53.613+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:53,613][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-13T20:34:53.854+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:53,853][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-13T20:34:53.905+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:53,905][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x30a43e19 run>"}
[2023-03-13T20:34:55.093+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:55,093][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.18}
[2023-03-13T20:34:55.216+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:55,216][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-13T20:34:55.319+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:55,318][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-13T20:34:57.042+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:57,042][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.024786s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-13T20:34:57.294+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:57,294][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.041893s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-13T20:34:57.775+0000] {subprocess.py:93} INFO - [2023-03-13T20:34:57,775][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.452183s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 0
[2023-03-13T20:35:06.603+0000] {subprocess.py:93} INFO - [2023-03-13T20:35:06,603][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.354176s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 50000
[2023-03-13T20:35:13.627+0000] {subprocess.py:93} INFO - [2023-03-13T20:35:13,627][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.292826s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 100000
[2023-03-13T20:35:20.447+0000] {subprocess.py:93} INFO - [2023-03-13T20:35:20,447][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.359803s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 150000
[2023-03-13T20:35:23.549+0000] {subprocess.py:93} INFO - [2023-03-13T20:35:23,549][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.212357s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 200000
[2023-03-13T20:35:26.195+0000] {subprocess.py:93} INFO - [2023-03-13T20:35:26,195][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.120124s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 250000
[2023-03-13T20:35:29.274+0000] {subprocess.py:93} INFO - [2023-03-13T20:35:29,274][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.168333s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 300000
[2023-03-13T20:35:32.042+0000] {subprocess.py:93} INFO - [2023-03-13T20:35:32,042][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.112757s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 350000
[2023-03-13T20:35:33.756+0000] {subprocess.py:93} INFO - [2023-03-13T20:35:33,756][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-13T20:35:34.040+0000] {subprocess.py:93} INFO - [2023-03-13T20:35:34,040][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-13T20:35:34.094+0000] {subprocess.py:93} INFO - [2023-03-13T20:35:34,094][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-13T20:35:34.251+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-13T20:35:34.283+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000027, start_date=20230313T203422, end_date=20230313T203534
[2023-03-13T20:35:34.336+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-13T20:35:34.351+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-14T09:28:10.373+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-14T09:28:10.385+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-14T09:28:10.385+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T09:28:10.386+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-14T09:28:10.386+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T09:28:10.408+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:27+00:00
[2023-03-14T09:28:10.411+0000] {standard_task_runner.py:55} INFO - Started process 25041 to run task
[2023-03-14T09:28:10.415+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:27+00:00', '--job-id', '541', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpmzlx3al9']
[2023-03-14T09:28:10.417+0000] {standard_task_runner.py:83} INFO - Job 541: Subtask Chargement_des_données_in_ELK
[2023-03-14T09:28:10.484+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [running]> on host dev
[2023-03-14T09:28:10.554+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:27+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:27+00:00
[2023-03-14T09:28:10.555+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-14T09:28:10.556+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-14T09:28:10.564+0000] {subprocess.py:86} INFO - Output:
[2023-03-14T09:28:10.651+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-14T09:28:10.921+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-14T09:28:34.688+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-14T09:28:34.809+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:34,805][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-14T09:28:34.820+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:34,819][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-14T09:28:35.266+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:35,265][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-14T09:28:37.761+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:37,760][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-14T09:28:38.672+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:38,672][INFO ][org.reflections.Reflections] Reflections took 244 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-14T09:28:40.229+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:40,228][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-14T09:28:40.644+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:40,641][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-14T09:28:40.887+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:40,886][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-14T09:28:40.947+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:40,947][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-14T09:28:40.951+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:40,951][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-14T09:28:41.155+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:41,154][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-14T09:28:41.249+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:41,248][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x495cee9f run>"}
[2023-03-14T09:28:42.356+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:42,356][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.1}
[2023-03-14T09:28:42.487+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:42,487][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-14T09:28:42.602+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:42,601][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-14T09:28:43.943+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:43,942][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.021967s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-14T09:28:44.140+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:44,139][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.036773s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-14T09:28:44.593+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:44,593][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.427187s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 0
[2023-03-14T09:28:51.804+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:51,804][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.251089s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 50000
[2023-03-14T09:28:55.144+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:55,144][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.114234s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 100000
[2023-03-14T09:28:58.062+0000] {subprocess.py:93} INFO - [2023-03-14T09:28:58,061][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.120641s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 150000
[2023-03-14T09:29:00.617+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:00,617][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.151527s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 200000
[2023-03-14T09:29:03.606+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:03,605][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.115799s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 250000
[2023-03-14T09:29:06.300+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:06,299][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.153295s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 300000
[2023-03-14T09:29:09.128+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:09,127][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.069991s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 350000
[2023-03-14T09:29:11.088+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:11,088][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-14T09:29:11.300+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:11,299][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-14T09:29:11.348+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:11,348][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-14T09:29:11.477+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-14T09:29:11.505+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000027, start_date=20230314T092810, end_date=20230314T092911
[2023-03-14T09:29:11.540+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-14T09:29:11.556+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-15T07:10:04.314+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-15T07:10:04.318+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [queued]>
[2023-03-15T07:10:04.319+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T07:10:04.319+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-15T07:10:04.319+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T07:10:04.329+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:27+00:00
[2023-03-15T07:10:04.331+0000] {standard_task_runner.py:55} INFO - Started process 117639 to run task
[2023-03-15T07:10:04.332+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:27+00:00', '--job-id', '664', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmprjxb5dnm']
[2023-03-15T07:10:04.333+0000] {standard_task_runner.py:83} INFO - Job 664: Subtask Chargement_des_données_in_ELK
[2023-03-15T07:10:04.362+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:27+00:00 [running]> on host dev
[2023-03-15T07:10:04.395+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:27+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:27+00:00
[2023-03-15T07:10:04.396+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-15T07:10:04.396+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-15T07:10:04.400+0000] {subprocess.py:86} INFO - Output:
[2023-03-15T07:10:04.435+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-15T07:10:04.557+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-15T07:10:16.475+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-15T07:10:16.536+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:16,535][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-15T07:10:16.542+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:16,542][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-15T07:10:16.777+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:16,777][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-15T07:10:17.575+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:17,573][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-15T07:10:18.016+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:18,016][INFO ][org.reflections.Reflections] Reflections took 48 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-15T07:10:18.760+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:18,760][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-15T07:10:18.965+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:18,964][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-15T07:10:19.071+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:19,071][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-15T07:10:19.105+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:19,104][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-15T07:10:19.107+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:19,106][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-15T07:10:19.218+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:19,217][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-15T07:10:19.233+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:19,232][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x43e48903 run>"}
[2023-03-15T07:10:19.838+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:19,838][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>0.6}
[2023-03-15T07:10:19.899+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:19,898][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-15T07:10:19.960+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:19,959][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-15T07:10:20.644+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:20,644][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.011457s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-15T07:10:20.730+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:20,730][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.001966s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-15T07:10:21.163+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:21,163][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-15T07:10:21.504+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:21,503][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-15T07:10:21.526+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:21,526][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-15T07:10:21.577+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-15T07:10:21.590+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000027, start_date=20230315T071004, end_date=20230315T071021
[2023-03-15T07:10:21.617+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-15T07:10:21.630+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
