[2023-03-13T19:31:22.080+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-13T19:31:22.094+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-13T19:31:22.094+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:31:22.094+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:31:22.094+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:31:22.118+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:33+00:00
[2023-03-13T19:31:22.121+0000] {standard_task_runner.py:55} INFO - Started process 35286 to run task
[2023-03-13T19:31:22.126+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:33+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp31xk4c_f']
[2023-03-13T19:31:22.130+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:31:22.202+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [running]> on host dev
[2023-03-13T19:31:22.281+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:33+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:33+00:00
[2023-03-13T19:31:22.283+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:31:22.284+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/usr/bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:31:22.293+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:31:22.295+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: /usr/bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:31:22.296+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:31:22.307+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:31:22.312+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000033, start_date=20230313T193122, end_date=20230313T193122
[2023-03-13T19:31:22.335+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 29 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 35286)
[2023-03-13T19:31:22.377+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:31:22.402+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T19:41:53.352+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-13T19:41:53.365+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-13T19:41:53.365+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:41:53.366+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:41:53.366+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:41:53.388+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:33+00:00
[2023-03-13T19:41:53.391+0000] {standard_task_runner.py:55} INFO - Started process 37157 to run task
[2023-03-13T19:41:53.396+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:33+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpzkvf69cu']
[2023-03-13T19:41:53.397+0000] {standard_task_runner.py:83} INFO - Job 77: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:41:53.463+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [running]> on host dev
[2023-03-13T19:41:53.533+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:33+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:33+00:00
[2023-03-13T19:41:53.535+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:41:53.536+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:41:53.545+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:41:53.547+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:41:53.548+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:41:53.559+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:41:53.565+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000033, start_date=20230313T194153, end_date=20230313T194153
[2023-03-13T19:41:53.586+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 77 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 37157)
[2023-03-13T19:41:53.607+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:41:53.636+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T20:03:23.601+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-13T20:03:23.614+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-13T20:03:23.614+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:03:23.614+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:03:23.614+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:03:23.638+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:33+00:00
[2023-03-13T20:03:23.641+0000] {standard_task_runner.py:55} INFO - Started process 40941 to run task
[2023-03-13T20:03:23.646+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:33+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpc671x3uw']
[2023-03-13T20:03:23.647+0000] {standard_task_runner.py:83} INFO - Job 189: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:03:23.714+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [running]> on host dev
[2023-03-13T20:03:23.794+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:33+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:33+00:00
[2023-03-13T20:03:23.796+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:03:23.796+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash -f /home/dev/etc/logstash/conf.d/data.conf']
[2023-03-13T20:03:23.805+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:03:23.807+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T20:03:23.807+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T20:03:23.818+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T20:03:23.822+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000033, start_date=20230313T200323, end_date=20230313T200323
[2023-03-13T20:03:23.841+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 189 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 40941)
[2023-03-13T20:03:23.857+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T20:03:23.877+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T20:37:00.103+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-13T20:37:00.115+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-13T20:37:00.116+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:37:00.116+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:37:00.116+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:37:00.136+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:33+00:00
[2023-03-13T20:37:00.139+0000] {standard_task_runner.py:55} INFO - Started process 47935 to run task
[2023-03-13T20:37:00.143+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:33+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpwbwh1ke_']
[2023-03-13T20:37:00.145+0000] {standard_task_runner.py:83} INFO - Job 301: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:37:00.207+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [running]> on host dev
[2023-03-13T20:37:00.282+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:33+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:33+00:00
[2023-03-13T20:37:00.284+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:37:00.286+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-13T20:37:00.295+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:37:00.387+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-13T20:37:00.684+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-13T20:37:27.882+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-13T20:37:28.139+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:28,131][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-13T20:37:28.154+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:28,153][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-13T20:37:28.703+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:28,703][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-13T20:37:31.027+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:31,026][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-13T20:37:32.450+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:32,449][INFO ][org.reflections.Reflections] Reflections took 247 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-13T20:37:34.619+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:34,618][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-13T20:37:35.187+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:35,184][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-13T20:37:35.427+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:35,427][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-13T20:37:35.503+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:35,503][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-13T20:37:35.508+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:35,507][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-13T20:37:35.725+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:35,724][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-13T20:37:35.781+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:35,780][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x52aaa6f run>"}
[2023-03-13T20:37:37.014+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:37,014][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.23}
[2023-03-13T20:37:37.176+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:37,176][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-13T20:37:37.302+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:37,301][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-13T20:37:38.996+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:38,995][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.026271s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-13T20:37:39.229+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:39,229][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.041161s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-13T20:37:39.756+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:39,755][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.488402s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 0
[2023-03-13T20:37:48.840+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:48,839][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.338457s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 50000
[2023-03-13T20:37:52.327+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:52,327][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.347532s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 100000
[2023-03-13T20:37:55.305+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:55,304][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.141384s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 150000
[2023-03-13T20:37:58.167+0000] {subprocess.py:93} INFO - [2023-03-13T20:37:58,167][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.208256s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 200000
[2023-03-13T20:38:03.995+0000] {subprocess.py:93} INFO - [2023-03-13T20:38:03,995][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.109593s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 250000
[2023-03-13T20:38:07.775+0000] {subprocess.py:93} INFO - [2023-03-13T20:38:07,775][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.164230s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 300000
[2023-03-13T20:38:10.793+0000] {subprocess.py:93} INFO - [2023-03-13T20:38:10,793][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.141237s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 350000
[2023-03-13T20:38:13.614+0000] {subprocess.py:93} INFO - [2023-03-13T20:38:13,613][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.123414s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 400000
[2023-03-13T20:38:16.695+0000] {subprocess.py:93} INFO - [2023-03-13T20:38:16,694][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-13T20:38:17.033+0000] {subprocess.py:93} INFO - [2023-03-13T20:38:17,032][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-13T20:38:17.092+0000] {subprocess.py:93} INFO - [2023-03-13T20:38:17,092][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-13T20:38:17.290+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-13T20:38:17.328+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000033, start_date=20230313T203700, end_date=20230313T203817
[2023-03-13T20:38:17.392+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-13T20:38:17.409+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-14T09:30:44.804+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-14T09:30:44.816+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-14T09:30:44.817+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T09:30:44.817+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-14T09:30:44.817+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T09:30:44.837+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:33+00:00
[2023-03-14T09:30:44.840+0000] {standard_task_runner.py:55} INFO - Started process 25687 to run task
[2023-03-14T09:30:44.845+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:33+00:00', '--job-id', '545', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmppvh07wd5']
[2023-03-14T09:30:44.846+0000] {standard_task_runner.py:83} INFO - Job 545: Subtask Chargement_des_données_in_ELK
[2023-03-14T09:30:44.919+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [running]> on host dev
[2023-03-14T09:30:44.990+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:33+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:33+00:00
[2023-03-14T09:30:44.991+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-14T09:30:44.992+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-14T09:30:45.000+0000] {subprocess.py:86} INFO - Output:
[2023-03-14T09:30:45.088+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-14T09:30:45.348+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-14T09:31:09.583+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-14T09:31:09.722+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:09,718][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-14T09:31:09.733+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:09,732][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-14T09:31:10.319+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:10,318][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-14T09:31:12.128+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:12,127][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-14T09:31:13.046+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:13,045][INFO ][org.reflections.Reflections] Reflections took 151 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-14T09:31:14.785+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:14,783][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-14T09:31:15.361+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:15,358][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-14T09:31:15.584+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:15,584][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-14T09:31:15.650+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:15,649][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-14T09:31:15.654+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:15,653][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-14T09:31:15.871+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:15,870][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-14T09:31:15.970+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:15,969][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x7be5c3ce run>"}
[2023-03-14T09:31:17.140+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:17,139][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.17}
[2023-03-14T09:31:17.300+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:17,299][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-14T09:31:17.458+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:17,457][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-14T09:31:19.119+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:19,118][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.022170s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-14T09:31:19.347+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:19,347][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.048942s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-14T09:31:19.899+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:19,899][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.523998s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 0
[2023-03-14T09:31:28.220+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:28,219][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.387726s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 50000
[2023-03-14T09:31:33.364+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:33,364][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.098562s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 100000
[2023-03-14T09:31:37.756+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:37,756][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.134395s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 150000
[2023-03-14T09:31:41.637+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:41,637][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.195117s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 200000
[2023-03-14T09:31:44.582+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:44,582][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.111997s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 250000
[2023-03-14T09:31:50.735+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:50,734][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.124783s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 300000
[2023-03-14T09:31:53.245+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:53,244][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.121794s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 350000
[2023-03-14T09:31:56.040+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:56,040][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.108906s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 400000
[2023-03-14T09:31:59.820+0000] {subprocess.py:93} INFO - [2023-03-14T09:31:59,820][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-14T09:32:00.176+0000] {subprocess.py:93} INFO - [2023-03-14T09:32:00,176][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-14T09:32:00.222+0000] {subprocess.py:93} INFO - [2023-03-14T09:32:00,221][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-14T09:32:00.396+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-14T09:32:00.423+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000033, start_date=20230314T093044, end_date=20230314T093200
[2023-03-14T09:32:00.483+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-14T09:32:00.496+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-15T07:10:43.714+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-15T07:10:43.720+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [queued]>
[2023-03-15T07:10:43.720+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T07:10:43.720+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-15T07:10:43.720+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T07:10:43.733+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:33+00:00
[2023-03-15T07:10:43.735+0000] {standard_task_runner.py:55} INFO - Started process 118019 to run task
[2023-03-15T07:10:43.737+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:33+00:00', '--job-id', '668', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpyb_klehj']
[2023-03-15T07:10:43.738+0000] {standard_task_runner.py:83} INFO - Job 668: Subtask Chargement_des_données_in_ELK
[2023-03-15T07:10:43.773+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:33+00:00 [running]> on host dev
[2023-03-15T07:10:43.815+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:33+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:33+00:00
[2023-03-15T07:10:43.816+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-15T07:10:43.816+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-15T07:10:43.821+0000] {subprocess.py:86} INFO - Output:
[2023-03-15T07:10:43.862+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-15T07:10:44.033+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-15T07:10:55.095+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-15T07:10:55.153+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:55,151][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-15T07:10:55.158+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:55,158][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-15T07:10:55.366+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:55,366][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-15T07:10:56.135+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:56,134][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-15T07:10:56.556+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:56,556][INFO ][org.reflections.Reflections] Reflections took 42 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-15T07:10:57.219+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:57,218][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-15T07:10:57.422+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:57,421][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-15T07:10:57.524+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:57,524][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-15T07:10:57.554+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:57,554][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-15T07:10:57.556+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:57,556][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-15T07:10:57.662+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:57,661][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-15T07:10:57.699+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:57,699][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x4fb0e857 run>"}
[2023-03-15T07:10:58.213+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:58,213][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>0.51}
[2023-03-15T07:10:58.275+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:58,275][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-15T07:10:58.329+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:58,329][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-15T07:10:58.988+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:58,987][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.012067s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-15T07:10:59.061+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:59,061][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.001278s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-15T07:10:59.612+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:59,611][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-15T07:10:59.864+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:59,864][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-15T07:10:59.886+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:59,885][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-15T07:10:59.925+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-15T07:10:59.937+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000033, start_date=20230315T071043, end_date=20230315T071059
[2023-03-15T07:10:59.964+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-15T07:10:59.972+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
