[2023-03-13T19:30:50.310+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-13T19:30:50.321+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-13T19:30:50.322+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:30:50.322+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:30:50.322+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:30:50.342+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:21+00:00
[2023-03-13T19:30:50.345+0000] {standard_task_runner.py:55} INFO - Started process 35025 to run task
[2023-03-13T19:30:50.349+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:21+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp4fb4ez0k']
[2023-03-13T19:30:50.351+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:30:50.416+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [running]> on host dev
[2023-03-13T19:30:50.481+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:21+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:21+00:00
[2023-03-13T19:30:50.483+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:30:50.483+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/usr/bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:30:50.491+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:30:50.492+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: /usr/bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:30:50.493+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:30:50.502+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:30:50.506+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000021, start_date=20230313T193050, end_date=20230313T193050
[2023-03-13T19:30:50.523+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 21 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 35025)
[2023-03-13T19:30:50.560+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:30:50.580+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T19:41:24.291+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-13T19:41:24.306+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-13T19:41:24.307+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:41:24.307+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:41:24.307+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:41:24.328+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:21+00:00
[2023-03-13T19:41:24.331+0000] {standard_task_runner.py:55} INFO - Started process 37033 to run task
[2023-03-13T19:41:24.336+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:21+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpjaz5kq39']
[2023-03-13T19:41:24.338+0000] {standard_task_runner.py:83} INFO - Job 69: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:41:24.404+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [running]> on host dev
[2023-03-13T19:41:24.472+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:21+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:21+00:00
[2023-03-13T19:41:24.474+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:41:24.475+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:41:24.483+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:41:24.485+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:41:24.485+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:41:24.495+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:41:24.500+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000021, start_date=20230313T194124, end_date=20230313T194124
[2023-03-13T19:41:24.521+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 69 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 37033)
[2023-03-13T19:41:24.547+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:41:24.567+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T20:02:50.411+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-13T20:02:50.425+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-13T20:02:50.426+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:02:50.426+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:02:50.426+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:02:50.447+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:21+00:00
[2023-03-13T20:02:50.451+0000] {standard_task_runner.py:55} INFO - Started process 40807 to run task
[2023-03-13T20:02:50.456+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:21+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpdy_j01g_']
[2023-03-13T20:02:50.459+0000] {standard_task_runner.py:83} INFO - Job 181: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:02:50.533+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [running]> on host dev
[2023-03-13T20:02:50.620+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:21+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:21+00:00
[2023-03-13T20:02:50.622+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:02:50.624+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash -f /home/dev/etc/logstash/conf.d/data.conf']
[2023-03-13T20:02:50.636+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:02:50.638+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T20:02:50.639+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T20:02:50.654+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T20:02:50.660+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000021, start_date=20230313T200250, end_date=20230313T200250
[2023-03-13T20:02:50.687+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 181 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 40807)
[2023-03-13T20:02:50.708+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T20:02:50.730+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T20:31:36.269+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-13T20:31:36.281+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-13T20:31:36.281+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:31:36.281+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:31:36.282+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:31:36.304+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:21+00:00
[2023-03-13T20:31:36.307+0000] {standard_task_runner.py:55} INFO - Started process 46690 to run task
[2023-03-13T20:31:36.312+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:21+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpzi0pivfi']
[2023-03-13T20:31:36.314+0000] {standard_task_runner.py:83} INFO - Job 293: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:31:36.385+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [running]> on host dev
[2023-03-13T20:31:36.486+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:21+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:21+00:00
[2023-03-13T20:31:36.490+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:31:36.493+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-13T20:31:36.511+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:31:36.615+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-13T20:31:36.912+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-13T20:32:05.632+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-13T20:32:05.792+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:05,788][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-13T20:32:05.806+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:05,805][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-13T20:32:06.411+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:06,411][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-13T20:32:08.734+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:08,733][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-13T20:32:09.766+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:09,765][INFO ][org.reflections.Reflections] Reflections took 149 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-13T20:32:11.506+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:11,505][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-13T20:32:12.184+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:12,177][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-13T20:32:12.519+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:12,518][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-13T20:32:12.604+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:12,604][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-13T20:32:12.609+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:12,609][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-13T20:32:12.841+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:12,840][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-13T20:32:12.889+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:12,888][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x53b5b303 run>"}
[2023-03-13T20:32:14.128+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:14,127][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.23}
[2023-03-13T20:32:14.299+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:14,298][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-13T20:32:14.434+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:14,433][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-13T20:32:16.179+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:16,178][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.030694s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-13T20:32:16.401+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:16,401][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.042243s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-13T20:32:16.911+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:16,910][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.478822s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 0
[2023-03-13T20:32:27.679+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:27,679][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.407714s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 50000
[2023-03-13T20:32:36.760+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:36,760][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.483560s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 100000
[2023-03-13T20:32:43.437+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:43,437][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.475203s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 150000
[2023-03-13T20:32:49.607+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:49,607][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.377758s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 200000
[2023-03-13T20:32:53.567+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:53,567][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.139998s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 250000
[2023-03-13T20:32:57.753+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:57,753][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-13T20:32:57.977+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:57,976][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-13T20:32:58.074+0000] {subprocess.py:93} INFO - [2023-03-13T20:32:58,069][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-13T20:32:58.281+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-13T20:32:58.311+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000021, start_date=20230313T203136, end_date=20230313T203258
[2023-03-13T20:32:58.343+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-13T20:32:58.358+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-14T09:25:50.951+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-14T09:25:50.963+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-14T09:25:50.963+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T09:25:50.964+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-14T09:25:50.964+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T09:25:50.985+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:21+00:00
[2023-03-14T09:25:50.988+0000] {standard_task_runner.py:55} INFO - Started process 24484 to run task
[2023-03-14T09:25:50.992+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:21+00:00', '--job-id', '537', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmph1hofjvi']
[2023-03-14T09:25:50.993+0000] {standard_task_runner.py:83} INFO - Job 537: Subtask Chargement_des_données_in_ELK
[2023-03-14T09:25:51.059+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [running]> on host dev
[2023-03-14T09:25:51.127+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:21+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:21+00:00
[2023-03-14T09:25:51.128+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-14T09:25:51.129+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-14T09:25:51.137+0000] {subprocess.py:86} INFO - Output:
[2023-03-14T09:25:51.225+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-14T09:25:51.521+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-14T09:26:15.308+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-14T09:26:15.426+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:15,423][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-14T09:26:15.437+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:15,436][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-14T09:26:15.915+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:15,915][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-14T09:26:17.618+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:17,610][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-14T09:26:18.384+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:18,383][INFO ][org.reflections.Reflections] Reflections took 122 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-14T09:26:19.802+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:19,801][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-14T09:26:20.293+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:20,291][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-14T09:26:20.553+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:20,552][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-14T09:26:20.627+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:20,627][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-14T09:26:20.632+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:20,631][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-14T09:26:20.827+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:20,826][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-14T09:26:20.892+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:20,892][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x26b30d40 run>"}
[2023-03-14T09:26:22.146+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:22,146][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.25}
[2023-03-14T09:26:22.278+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:22,278][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-14T09:26:22.389+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:22,388][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-14T09:26:23.942+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:23,941][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.021923s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-14T09:26:24.138+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:24,138][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.040510s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-14T09:26:24.575+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:24,575][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.409545s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 0
[2023-03-14T09:26:33.123+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:33,123][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.369039s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 50000
[2023-03-14T09:26:37.325+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:37,325][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.126069s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 100000
[2023-03-14T09:26:39.976+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:39,976][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.106095s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 150000
[2023-03-14T09:26:42.423+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:42,423][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.109019s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 200000
[2023-03-14T09:26:44.892+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:44,892][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.133035s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 250000
[2023-03-14T09:26:56.768+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:56,768][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-14T09:26:57.194+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:57,193][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-14T09:26:57.260+0000] {subprocess.py:93} INFO - [2023-03-14T09:26:57,260][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-14T09:26:57.412+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-14T09:26:57.441+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000021, start_date=20230314T092550, end_date=20230314T092657
[2023-03-14T09:26:57.489+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-14T09:26:57.506+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-15T07:09:25.766+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-15T07:09:25.771+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [queued]>
[2023-03-15T07:09:25.771+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T07:09:25.771+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-15T07:09:25.771+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T07:09:25.781+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:21+00:00
[2023-03-15T07:09:25.782+0000] {standard_task_runner.py:55} INFO - Started process 117337 to run task
[2023-03-15T07:09:25.784+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:21+00:00', '--job-id', '660', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpvtibrqpq']
[2023-03-15T07:09:25.785+0000] {standard_task_runner.py:83} INFO - Job 660: Subtask Chargement_des_données_in_ELK
[2023-03-15T07:09:25.813+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:21+00:00 [running]> on host dev
[2023-03-15T07:09:25.848+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:21+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:21+00:00
[2023-03-15T07:09:25.849+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-15T07:09:25.849+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-15T07:09:25.853+0000] {subprocess.py:86} INFO - Output:
[2023-03-15T07:09:25.890+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-15T07:09:26.010+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-15T07:09:37.048+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-15T07:09:37.120+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:37,118][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-15T07:09:37.126+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:37,125][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-15T07:09:37.362+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:37,361][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-15T07:09:38.146+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:38,145][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-15T07:09:38.540+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:38,539][INFO ][org.reflections.Reflections] Reflections took 52 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-15T07:09:39.205+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:39,205][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-15T07:09:39.446+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:39,445][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-15T07:09:39.556+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:39,555][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-15T07:09:39.585+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:39,584][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-15T07:09:39.586+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:39,586][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-15T07:09:39.688+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:39,688][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-15T07:09:39.713+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:39,712][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x7cd532bc run>"}
[2023-03-15T07:09:40.181+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:40,181][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>0.47}
[2023-03-15T07:09:40.238+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:40,237][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-15T07:09:40.274+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:40,273][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-15T07:09:41.013+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:41,013][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.012770s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-15T07:09:41.117+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:41,117][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.001401s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-15T07:09:41.634+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:41,633][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-15T07:09:41.826+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:41,825][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-15T07:09:41.850+0000] {subprocess.py:93} INFO - [2023-03-15T07:09:41,850][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-15T07:09:41.902+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-15T07:09:41.917+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000021, start_date=20230315T070925, end_date=20230315T070941
[2023-03-15T07:09:41.969+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-15T07:09:41.976+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
