[2023-03-13T19:31:13.641+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-13T19:31:13.654+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-13T19:31:13.654+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:31:13.654+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:31:13.654+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:31:13.676+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:30+00:00
[2023-03-13T19:31:13.679+0000] {standard_task_runner.py:55} INFO - Started process 35235 to run task
[2023-03-13T19:31:13.684+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:30+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpijr9r8n_']
[2023-03-13T19:31:13.686+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:31:13.752+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [running]> on host dev
[2023-03-13T19:31:13.822+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:30+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:30+00:00
[2023-03-13T19:31:13.824+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:31:13.825+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/usr/bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:31:13.833+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:31:13.834+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: /usr/bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:31:13.835+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:31:13.846+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:31:13.851+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000030, start_date=20230313T193113, end_date=20230313T193113
[2023-03-13T19:31:13.874+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 27 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 35235)
[2023-03-13T19:31:13.899+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:31:13.927+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T19:41:46.075+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-13T19:41:46.087+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-13T19:41:46.087+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:41:46.088+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:41:46.088+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:41:46.109+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:30+00:00
[2023-03-13T19:41:46.112+0000] {standard_task_runner.py:55} INFO - Started process 37120 to run task
[2023-03-13T19:41:46.116+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:30+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpl8njpvja']
[2023-03-13T19:41:46.118+0000] {standard_task_runner.py:83} INFO - Job 75: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:41:46.181+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [running]> on host dev
[2023-03-13T19:41:46.252+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:30+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:30+00:00
[2023-03-13T19:41:46.254+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:41:46.255+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:41:46.263+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:41:46.265+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:41:46.265+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:41:46.275+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:41:46.279+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000030, start_date=20230313T194146, end_date=20230313T194146
[2023-03-13T19:41:46.298+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 75 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 37120)
[2023-03-13T19:41:46.327+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:41:46.348+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T20:03:15.606+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-13T20:03:15.619+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-13T20:03:15.619+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:03:15.619+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:03:15.620+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:03:15.648+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:30+00:00
[2023-03-13T20:03:15.652+0000] {standard_task_runner.py:55} INFO - Started process 40881 to run task
[2023-03-13T20:03:15.656+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:30+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpv193oh7i']
[2023-03-13T20:03:15.658+0000] {standard_task_runner.py:83} INFO - Job 187: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:03:15.727+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [running]> on host dev
[2023-03-13T20:03:15.797+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:30+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:30+00:00
[2023-03-13T20:03:15.799+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:03:15.800+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash -f /home/dev/etc/logstash/conf.d/data.conf']
[2023-03-13T20:03:15.808+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:03:15.810+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T20:03:15.811+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T20:03:15.821+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T20:03:15.825+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000030, start_date=20230313T200315, end_date=20230313T200315
[2023-03-13T20:03:15.843+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 187 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 40881)
[2023-03-13T20:03:15.867+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T20:03:15.888+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T20:35:41.095+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-13T20:35:41.108+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-13T20:35:41.108+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:35:41.109+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:35:41.109+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:35:41.131+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:30+00:00
[2023-03-13T20:35:41.134+0000] {standard_task_runner.py:55} INFO - Started process 47610 to run task
[2023-03-13T20:35:41.139+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:30+00:00', '--job-id', '299', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp54ezh4l4']
[2023-03-13T20:35:41.141+0000] {standard_task_runner.py:83} INFO - Job 299: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:35:41.208+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [running]> on host dev
[2023-03-13T20:35:41.278+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:30+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:30+00:00
[2023-03-13T20:35:41.280+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:35:41.280+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-13T20:35:41.289+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:35:41.382+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-13T20:35:41.652+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-13T20:36:08.174+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-13T20:36:08.349+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:08,345][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-13T20:36:08.364+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:08,363][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-13T20:36:09.091+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:09,091][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-13T20:36:11.488+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:11,475][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-13T20:36:12.436+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:12,435][INFO ][org.reflections.Reflections] Reflections took 177 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-13T20:36:14.235+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:14,233][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-13T20:36:14.758+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:14,756][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-13T20:36:15.032+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:15,031][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-13T20:36:15.110+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:15,110][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-13T20:36:15.115+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:15,114][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-13T20:36:15.315+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:15,314][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-13T20:36:15.355+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:15,355][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x5dd4a305 run>"}
[2023-03-13T20:36:16.602+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:16,601][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.24}
[2023-03-13T20:36:16.736+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:16,735][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-13T20:36:16.844+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:16,844][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-13T20:36:18.767+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:18,766][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.035886s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-13T20:36:19.044+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:19,044][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.051693s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-13T20:36:19.614+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:19,614][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.529125s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 0
[2023-03-13T20:36:27.996+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:27,996][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.333078s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 50000
[2023-03-13T20:36:33.267+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:33,267][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.443755s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 100000
[2023-03-13T20:36:37.000+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:36,999][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.332468s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 150000
[2023-03-13T20:36:40.251+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:40,251][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.122276s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 200000
[2023-03-13T20:36:43.687+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:43,686][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.160668s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 250000
[2023-03-13T20:36:46.307+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:46,307][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.159595s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 300000
[2023-03-13T20:36:48.898+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:48,898][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.177037s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 350000
[2023-03-13T20:36:52.283+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:52,283][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-13T20:36:52.552+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:52,551][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-13T20:36:52.603+0000] {subprocess.py:93} INFO - [2023-03-13T20:36:52,602][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-13T20:36:52.875+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-13T20:36:52.907+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000030, start_date=20230313T203541, end_date=20230313T203652
[2023-03-13T20:36:52.965+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-13T20:36:52.982+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-14T09:29:18.328+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-14T09:29:18.341+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-14T09:29:18.341+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T09:29:18.341+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-14T09:29:18.341+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T09:29:18.362+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:30+00:00
[2023-03-14T09:29:18.365+0000] {standard_task_runner.py:55} INFO - Started process 25326 to run task
[2023-03-14T09:29:18.369+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:30+00:00', '--job-id', '543', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp9ohinq_n']
[2023-03-14T09:29:18.371+0000] {standard_task_runner.py:83} INFO - Job 543: Subtask Chargement_des_données_in_ELK
[2023-03-14T09:29:18.441+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [running]> on host dev
[2023-03-14T09:29:18.513+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:30+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:30+00:00
[2023-03-14T09:29:18.515+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-14T09:29:18.516+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-14T09:29:18.524+0000] {subprocess.py:86} INFO - Output:
[2023-03-14T09:29:18.610+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-14T09:29:18.863+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-14T09:29:44.138+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-14T09:29:44.271+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:44,267][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-14T09:29:44.285+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:44,285][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-14T09:29:44.900+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:44,900][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-14T09:29:46.663+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:46,662][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-14T09:29:47.502+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:47,501][INFO ][org.reflections.Reflections] Reflections took 147 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-14T09:29:48.974+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:48,973][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-14T09:29:49.455+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:49,452][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-14T09:29:49.699+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:49,698][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-14T09:29:49.762+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:49,762][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-14T09:29:49.766+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:49,766][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-14T09:29:49.973+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:49,972][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-14T09:29:50.037+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:50,036][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x774c34b0 run>"}
[2023-03-14T09:29:51.204+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:51,204][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.16}
[2023-03-14T09:29:51.345+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:51,345][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-14T09:29:51.462+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:51,461][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-14T09:29:52.787+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:52,786][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.022581s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-14T09:29:53.010+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:53,010][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.044659s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-14T09:29:53.592+0000] {subprocess.py:93} INFO - [2023-03-14T09:29:53,592][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.542385s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 0
[2023-03-14T09:30:01.949+0000] {subprocess.py:93} INFO - [2023-03-14T09:30:01,949][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.335089s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 50000
[2023-03-14T09:30:09.115+0000] {subprocess.py:93} INFO - [2023-03-14T09:30:09,115][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.422030s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 100000
[2023-03-14T09:30:14.392+0000] {subprocess.py:93} INFO - [2023-03-14T09:30:14,391][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.469231s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 150000
[2023-03-14T09:30:21.277+0000] {subprocess.py:93} INFO - [2023-03-14T09:30:21,276][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.353223s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 200000
[2023-03-14T09:30:24.933+0000] {subprocess.py:93} INFO - [2023-03-14T09:30:24,933][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.361056s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 250000
[2023-03-14T09:30:27.750+0000] {subprocess.py:93} INFO - [2023-03-14T09:30:27,750][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.116684s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 300000
[2023-03-14T09:30:30.319+0000] {subprocess.py:93} INFO - [2023-03-14T09:30:30,318][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.128601s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 350000
[2023-03-14T09:30:36.936+0000] {subprocess.py:93} INFO - [2023-03-14T09:30:36,936][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-14T09:30:37.176+0000] {subprocess.py:93} INFO - [2023-03-14T09:30:37,176][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-14T09:30:37.241+0000] {subprocess.py:93} INFO - [2023-03-14T09:30:37,240][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-14T09:30:37.416+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-14T09:30:37.448+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000030, start_date=20230314T092918, end_date=20230314T093037
[2023-03-14T09:30:37.478+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-14T09:30:37.498+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-15T07:10:24.350+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-15T07:10:24.354+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [queued]>
[2023-03-15T07:10:24.354+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T07:10:24.355+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-15T07:10:24.355+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T07:10:24.364+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:30+00:00
[2023-03-15T07:10:24.366+0000] {standard_task_runner.py:55} INFO - Started process 117858 to run task
[2023-03-15T07:10:24.368+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:30+00:00', '--job-id', '666', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpncmg1o8g']
[2023-03-15T07:10:24.368+0000] {standard_task_runner.py:83} INFO - Job 666: Subtask Chargement_des_données_in_ELK
[2023-03-15T07:10:24.399+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:30+00:00 [running]> on host dev
[2023-03-15T07:10:24.432+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:30+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:30+00:00
[2023-03-15T07:10:24.433+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-15T07:10:24.433+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-15T07:10:24.437+0000] {subprocess.py:86} INFO - Output:
[2023-03-15T07:10:24.475+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-15T07:10:24.598+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-15T07:10:35.424+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-15T07:10:35.501+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:35,499][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-15T07:10:35.508+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:35,508][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-15T07:10:35.766+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:35,766][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-15T07:10:36.678+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:36,678][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-15T07:10:37.116+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:37,116][INFO ][org.reflections.Reflections] Reflections took 67 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-15T07:10:37.853+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:37,853][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-15T07:10:38.127+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:38,126][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-15T07:10:38.239+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:38,239][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-15T07:10:38.271+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:38,271][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-15T07:10:38.273+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:38,273][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-15T07:10:38.369+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:38,369][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-15T07:10:38.402+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:38,402][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x27dc6263 run>"}
[2023-03-15T07:10:38.892+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:38,892][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>0.49}
[2023-03-15T07:10:38.948+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:38,947][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-15T07:10:38.980+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:38,980][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-15T07:10:39.745+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:39,745][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.012063s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-15T07:10:39.838+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:39,837][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.001895s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-15T07:10:40.331+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:40,330][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-15T07:10:40.543+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:40,542][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-15T07:10:40.567+0000] {subprocess.py:93} INFO - [2023-03-15T07:10:40,567][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-15T07:10:40.626+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-15T07:10:40.642+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000030, start_date=20230315T071024, end_date=20230315T071040
[2023-03-15T07:10:40.682+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-15T07:10:40.688+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
